### ISSUE TITLE
showing amount of events in the calendar

### ISSUE THREAD

**Issue by bimiriya** [nizarmah/calendar-javascript-lib#13]
Is there any way to show the amount of events each day has in the calendar cells?

**Comment by nizarmah** [comment]
Well, not yet, I can implement it by the end of this week though. I have some exams, but should be able to find the time for it during this weekend.

I really care about the design and the functionality, so I will implement this suggestion with at max having 10 events, or it shall show 10+... Hopefully, if it looks good with 100+, I will implement that instead.

Thanks for the suggestion, and I hope you can wait a week at max for its implementation.

**Comment by bimiriya** [comment]
Thank you very much !!!

**Comment by nizarmah** [comment]
Hello, I have finished the new feature, just did it today.
I made it show 9+ events per day... I did this since the maximum events per day are approximately 24 events. So I went with 9+ since it sounded like a reasonable number with a pretty look.

Have a good day! Oh, and here's a preview.
I updated the examples if you wish to take a look at `examples/normal_organizer.html`. That example is the one previewed in the screenshot below.

![image](https://user-images.githubusercontent.com/5631091/46919860-431de980-cfee-11e8-9d79-51cff4385cc0.png)
