### ISSUE TITLE
Calendar does not display all events correctly

### ISSUE THREAD

**Issue by NightlandDriver** [nizarmah/calendar-javascript-lib#24]
**Describe the bug**
I have several events that are in a database, some go over several days, so they are in the database again for each day.
The whole thing also works flawlessly, unfortunately neither the time nor the link is displayed there.

Then I also have events that are not displayed at all.
I have attached some screenshots, logs and code here.

**Expected behavior**
All events with all links and times should be displayed.

**Screenshots**
[ImgBB: Event-in-the-next-year-is-not-displayed](https://ibb.co/ynq7tP3)
[ImgBB: Event-is-displayed-without-information-Month-before](https://ibb.co/vzvfx1z)
[ImgBB: Event-is-displayed-without-information](https://ibb.co/wwxv1Dj)

**Code & Logs**
Source Code: [Pastebin: Source from Calendar.php](https://pastebin.com/jwKx7HMW)
Log Data[]: [Pastebin: Caldendar Data Array Log](https://pastebin.com/0cBs2B5V)

**Desktop (please complete the following information):**
 - OS: [Windows, Android]
 - Browser [all]
 - Version [newest]

**Comment by nizarmah** [comment]
Hey @NightlandDriver! 
Sorry to hear that you're running into issues.

So, my first guess, looking at the log data, would be the `01`, `02`, `03`, etc... Those need to be `1` or `2` instead. A similar issue has been opened about a similar problem, cf [comment](https://github.com/nizarmah/calendar-javascript-lib/issues/21#issuecomment-703772271).

I should probably create a pull request for it, but it's an easy contribution for people who want to contribute, which is why I haven't.

Anyway, in case the problem is still happening, can you please share the dumped data from PHP instead or the console log data? It would be more helpful to indicate any problem with the data's structure 👍🏼

**Comment by NightlandDriver** [comment]
Hey

Thanks for the quick reply, now all events are displayed correctly.
