### ISSUE TITLE
"Feburary" is misspelled. 

### ISSUE THREAD

**Issue by sbennett08** [nizarmah/calendar-javascript-lib#28]
Should be an easy fix here for you :)

We've noticed that the month "February" is misspelled as "Feburary".
We are using a Windows 10 OS and a Chrome browser (version 88). 

I'm pretty sure this month is generated by your code when the calendar is printed out? If not, let me know and I'll take another look at the code on our end.

Great calendar widget by the way. It's just what we needed :)

![Capture](https://user-images.githubusercontent.com/55404397/108546517-1523d080-729e-11eb-991b-e628f0316991.PNG)

**Comment by nizarmah** [comment]
@sbennett08 😂 thanks for catching it! I have a lot of changes to address, but I'll be sure to address this one first 😃 

> Great calendar widget by the way. It's just what we needed :)

Thank you! ❤️ This means a lot!

**Comment by nizarmah** [comment]
@sbennett08 alright, so I looked into the issue more closely, and here's what I found out:

### Problem

The JavaScript has no problems:
https://github.com/nizarmah/calendar-javascript-lib/blob/ae99e849ae55dacb90aeb6eaa21e1b90e92d516f/calendarorganizer.js#L30

As you can see, the month is mentioned properly, `February`.

However, the problem seems to be the README. 
https://github.com/nizarmah/calendar-javascript-lib/blob/ae99e849ae55dacb90aeb6eaa21e1b90e92d516f/README.md#L71
https://github.com/nizarmah/calendar-javascript-lib/blob/ae99e849ae55dacb90aeb6eaa21e1b90e92d516f/README.md#L110

### Solution

So there's two ways to solve the issue.

You can either remove the declared `months` attribute, which you don't need unless you're making changing to how the months are displayed. 

Or you can update the settings from `Feburary` to `February` 👍🏼 

---

I also opened a pull request in order to resolve the issue which you can find below. #29

---

I'm closing this issue 😃 

Thank you a lot for raising it, and I'm glad that the widget is being used ❤️ 

Have a wonderful day 🚀
