### ISSUE TITLE
library not working on Internet Explorer

### ISSUE THREAD

**Issue by sakarthapa1** [nizarmah/calendar-javascript-lib#3]
<div> appears blank on IE
version: 11.125.16299.0
update version: 11.0.49 (KB4052978)
Product ID: 00150-200000-00003-AA459

**Comment by nizarmah** [comment]
Hello, may you kindly give me the version of Internet Explorer that the calendar does not work on?
Thanks in advance.

**Comment by sakarthapa1** [comment]
div appears blank on IE version: 11.125.16299.0 update version: 11.0.49 (KB4052978) Product ID: 00150-200000-00003-AA459

**Comment by nizarmah** [comment]
Hello again,

I am sorry for the delay sir. I have been busy with work this whole week. I will be sure to work on the issue tomorrow and get it fixed on IE 11 and 10. Hopefully, maybe 9 too.

Kindly accept my apologies.

**Comment by sakarthapa1** [comment]
Hello again,
First of all thank you for your response and great library. No problem
sir,I understand your busy schedule. I am waiting for the issue to be
solved. Hope you will fix it soon.

Thank you.

**Comment by nizarmah** [comment]
Hello,

It took some head bashing but finally I figured it out.
I was only able to support IE 10 and 11; IE 9 support was a bust, sorry about that.

Anyway, just a tip in case you ever use `appendChild` in JavaScript; to support IE 10 and 11 and even 9, you have to use `appendChild(element.cloneNode(true))`. That way the appended is an actual clone of the whole element and its contents. If the element weren't to cloned, then IE would not actually append them, due to some issues.

Thanks for letting me know about the bug.
If you have any other suggestions or bug reports, I am all ears.

Have a good day!

**Comment by sakarthapa1** [comment]
Hello,

Thank you for  the solution.
