### ISSUE TITLE
adding current date

### ISSUE THREAD

**Issue by kuropanda24** [nizarmah/calendar-javascript-lib#4]
I just realize your code always update the current date and you did not declared a class to specify which is the current date. Do you know any solution for this? Thanks!

**Comment by nizarmah** [comment]
Hello,

What do you mean by did not specify a class to add a current date? Please be more elaborative so I can start working on what you need :).

**Comment by kuropanda24** [comment]
Hello,

I realized you never specified a class for the current date of today. For example today is 10th of january, If i click next and click any date of the month, and go back to January again. The current date is not 10th of january anymore because the code does not seem to have a variable or class for specification. 

Thanks

**Comment by nizarmah** [comment]
Hello again,

If I understood correctly, you are changing the current date, by pressing on let us assume 2nd of January and then switching month to February and back to January.

I am gonna assume what is active is January the 2nd. This is done in order to keep track of the events at a specific day between months. That way I can switch months and make sure that there are no events on that specific day for like 2 months or 5 months in a row, etc...

Please let me know if I understood that wrong, or not.

**Comment by kuropanda24** [comment]
Hello,

Sorry that was not my point. what I'm trying to say  is that I want your calendar to always have a current date. For example today is 11th of january. The number 11 on the calendar will be color red as an identifier of today's date. So if i click next of the calendar, then go back again to january, the current date did not change which is the ideal of the calendar. However, the calendar that you have right now does not have this.

Thanks

**Comment by nizarmah** [comment]
Hello!

I finally had the time to add it. Excuse my delay.
I made it look like a small underline under the current day.

Thanks for your suggestion. If you have anything else, kindly, let me know.

Have a good day!
