### ISSUE TITLE
Text for empty results?

### ISSUE THREAD

**Issue by enlivenapp** [nizarmah/calendar-javascript-lib#6]
Hi there,

I'm looking to have a small notice when there's no data for a given day rather than it being blank.

I've tinkered with it a bit, but I'm having issues getting such a thing to work.

Any help in that direction would be awesome.  

Thanks.

**Comment by nizarmah** [comment]
Hello sir,

I am extremely sorry I wasn't able to reply lately. I just saw the issue today; I wasn't able to check my email address the last 3 days.

So you want like a timing schedule to appear right? But have no data inside it?
That way the organizer is not blank, but shows the schedule if it is occupied or not?

I hope you can elaborate more in order for me to be helpful.

Have a good day!

**Comment by enlivenapp** [comment]
Hi @nizarmah 

No worries about delays.  We all have them.

So, the image below is a good example.  So instead of it being blank/empty, because there are no events that day, Something there (even editable to someone's needs) like "no schedule today" would be good.

![screen shot 2018-04-24 at 9 54 06 am](https://user-images.githubusercontent.com/3036663/39191687-795ecf18-47a5-11e8-9f7b-9d5ba2812f19.png)

**Comment by nizarmah** [comment]
Hello again,

First of all I gotta say, I adore that color choice.
I need to point out though, does the library look as it should ? Cause the screenshot you took looks a bit weird from my stance, a bit buggy.

I didn't have an idea of what you'd like to write if the organizer was empty. So I went ahead and created a placeholder option.
You can check both examples, `normal_organizer.html` and `custom_placeholder_organizer.html`.

In case you want to remove the placeholder, just enter Blank placeholder ""; it should do the job.
Otherwise, enter your own code for the placeholder and it'll preview instead.

Have a wonderful day, and thanks for your great suggestion.

Kindly, let me know if you run into any issues.

**Comment by enlivenapp** [comment]
Thank you!

I need both to be horizontal.  so I used the .wrapper CSS selector you used in previous versions.   I'm also on a Mac using safari, so that may be different from what you're using.

I'm building an appointment management site so if there's appointments available, I use the "buttons" for a client to choose the time, if there's no appointments available, I needed to indicate that as well.

Thanks a bunch!

**Comment by enlivenapp** [comment]
Here's a wider screenshot of what I'm working on.   Thanks a bunch again!

![screen shot 2018-04-26 at 12 52 18 pm](https://user-images.githubusercontent.com/3036663/39319969-b3db85e4-4950-11e8-91d5-f63613cd92af.png)

**Comment by nizarmah** [comment]
Oh my gosh! This looks freaking amazing!

Oh, since you're using Appointments, you can go ahead and change the _No events on this day_ text to whatever you want, or maybe a button to add new appointments, I made an example about that in the _examples_ folder. 

I made it possible to change the No events on this day HTML easily; if you want the same design just different text, use `<li>No appointments on this day</li>`.
Otherwise, if you want to add a Button to create appointments, you can go ahead and check the Example, where I created a custom Add Event button.

Ah safari, damn it, this might be why it isn't looking right.
Okay, well, if you end up fixing anything, let me know, just send me a Pull Request.

Otherwise, I'll need you to wait on me a week or two till my final exams are done. Once they are, I'll fix the design on a peer's Mac at work, because I sadly do not have any Apple devices.

But I love what you're working on, and please do share when you go online!

**Comment by nizarmah** [comment]
Oh, never mind me about adding a custom button, you have specific appointment schedules, or not. 
Well, you can always change the JavaScript source or the Placeholder to make it say Appointments.

Good luck with your thing!
