### ISSUE TITLE
Events not showing on the orginizer or in the calendar

### ISSUE THREAD

**Issue by fjparedesb** [nizarmah/calendar-javascript-lib#7]
I load a calendar and an organizer and fill the data with ajax, but the events don't show after the data is filled neidther in the organizer and in the calendar
[calendarorganizer.txt](https://github.com/nizarmah/calendar-javascript-lib/files/1943495/calendarorganizer.txt)

**Comment by nizarmah** [comment]
Hello,

I was looking into your code, and apparently, you have been initializing the Organizer with empty server data. Now, I see that you are trying to get them via Ajax, but after you are getting them with ajax, you are not updating the Organizer's Data with the new data.

In order to use Ajax, I have had a small tutorial on the README.md.
What you're gonna want to do is, not initialize the Organizer until you have actual data from an Ajax request on Load.

Then, you want to setup an On Month Change Event Listener in order to change the Data according to the Month you are on.

```
organizer.onMonthChange = function (callback) {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
            // TODO : Change the Organizer's Data to the new Data
            // TODO : that you just grabbed from the Ajax Request

            organizer.data = this.responseText;

            // TODO : Call the Callback to display the Data
            callback();
        }
    };
    xhttp.open("GET", "someurl.json", true);
    xhttp.send();
};
```

There is also an example regarding that. I hope it works, have a good day!

**Comment by nizarmah** [comment]
Please let me know when your problem is used after reading the example so that we close the issue.

**Comment by nizarmah** [comment]
Are you still facing an issue ? Or not ?

It is much better if you assist me in closing the issue, rather keeping it open.

**Comment by fjparedesb** [comment]
Sorry Nizar

It was resolved, it's ok it was closed

Thanks
